# Site settings
title: 朱海的个人简历
name: 朱海
description: 推荐算法工程师 | 中国科学技术大学硕士
url: "https://zhuhaibest.github.io"
baseurl: ""
repository: zhuhai-ustc/zhuhaibest.github.io

# Build settings
markdown: kramdown
theme: jekyll-theme-primer

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Social settings
github_username: zhuhai-ustc

# Social icons (shown in footer)
social:
  - icon: github
    link: "https://github.com/zhuhai-ustc"
  - icon: envelope
    link: "mailto:1132863306@qq.com"